### ISSUE TITLE
she mandzukia

### ISSUE THREAD

**Issue by mariam-ts** [tatotab/_Tetris#1]
vis atyueb? eg tetrisi jgufshi gaaketeeeeeeeeeeeeeee da daisakutre?

**Comment by tatotab** [comment]
i deman public apology!

**Comment by mariam-ts** [comment]
bloook tato

**Comment by mariam-ts** [comment]
mblokaavs xlxnoo mblokaavs, ro chemma xmam tqventan ar moagwioss

**Comment by tatotab** [comment]
please assist mariam, she cannot find way back to asatiani

**Comment by mariam-ts** [comment]
ai ukve warmosaxvit megobrebs elaparakeba

**Comment by mariam-ts** [comment]
su garekaa

**Comment by tatotab** [comment]
bitch bye

**Comment by mariam-ts** [comment]
> please assist mariam, she cannot find way back to asatiani

mariam is a dictator aaaa finish? :D:D:D

**Comment by mariam-ts** [comment]
> bitch bye

luka shexe ra mitxra bitcho

**Comment by tatotab** [comment]
fanduri ginda?

**Comment by mariam-ts** [comment]
tato gceeeeeeeeem :DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD washale es

**Comment by tatotab** [comment]
am repositorys sheni piradi problemebis gamo ver wavshli, qabbatono mariam!

**Comment by mariam-ts** [comment]
repo ara idioto issue :DDDDDD
